language: node_js  #设置语言

node_js: stable  #设置相应的版本

# 缓存依赖，节省持续集成时间
cache:
  directories:
    - node_modules
    - themes

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "yrxwin"  #修改name
  - git config user.email "mikeyrxwin@gmail.com"  #修改email
  - git add .
  - git commit -m "Site updated:\ $(date -u '+%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - develop  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/yrxwin/yrxwin.github.io.git  #设置GH_REF，注意更改yourname
