# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: XingXing Park
subtitle: 猩猩的乐园
description: 技术面试问题详解
keywords: "Leetcode, cpp, python, xingxingpark, interview, solution, 面试, system design, java, data structure, algorithm"
author: 猩猩的乐园
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://xingxingpark.com
root: /
# permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [baidu_verify_ajCCBIMjTA.html]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: Leetcode
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next7.0.1

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: git@github.com:yrxwin/yrxwin.github.io.git
    branch: master
    message:
  - type: baidu_url_submitter

# RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

# search engine
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# baidu 主动推送
baidu_url_submit:
  count: 2 ## 提交最新的一个链接
  host: xingxingpark.com ## 在百度站长平台中注册的域名
  token: 7whXmTLKVBu3WuDH ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

# local search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# hexo-related-popular-posts Specify option to use popular articles
# Add account information of Google Anakytics API
popularPosts:
  googleAnalyticsAPI:
    clientId:    112818765216157412274         # google analytics API Service account acquired with
    serviceEmail:  firebase-adminsdk-oq836@yrxwin.iam.gserviceaccount.com      # E-mail address obtained with the google analytics API
    key:  /ga.pem    # With the google analytics API Path of acquired pem file
    viewId:  172387417                                       # View ID tied with google analytics
    dateRange:  30                                          # (Optional) Time period (days) to count PV number Default is 30
    expiresDate:  10                                        # (Option) Cache file expiration date Days) Default is 10
